// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phase_2_back_end.Models;

namespace phase_2_back_end.Migrations
{
    [DbContext(typeof(ApplicationDatabase))]
    [Migration("20200819080216_FixRltshipBtwCanvasColordata")]
    partial class FixRltshipBtwCanvasColordata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("phase_2_back_end.Models.Canvas", b =>
                {
                    b.Property<int>("CanvasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("CanvasID");

                    b.ToTable("Canvas");
                });

            modelBuilder.Entity("phase_2_back_end.Models.ColorData", b =>
                {
                    b.Property<int>("ColorDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CanvasID")
                        .HasColumnType("int");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.HasKey("ColorDataID");

                    b.HasIndex("CanvasID");

                    b.ToTable("ColorData");
                });

            modelBuilder.Entity("phase_2_back_end.Models.ColorData", b =>
                {
                    b.HasOne("phase_2_back_end.Models.Canvas", "Canvas")
                        .WithMany("ColorData")
                        .HasForeignKey("CanvasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
