// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phase_2_back_end.Database;

namespace phase_2_back_end.Migrations
{
    [DbContext(typeof(ApplicationDatabase))]
    [Migration("20200810075230_Improved table structure")]
    partial class Improvedtablestructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("phase_2_back_end.Database.Canvas", b =>
                {
                    b.Property<int>("PictureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PictureID");

                    b.ToTable("Canvas");
                });

            modelBuilder.Entity("phase_2_back_end.Database.Matrix", b =>
                {
                    b.Property<int>("RowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CanvasPictureID")
                        .HasColumnType("int");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.HasKey("RowID");

                    b.HasIndex("CanvasPictureID");

                    b.ToTable("Matrices");
                });

            modelBuilder.Entity("phase_2_back_end.Database.Matrix", b =>
                {
                    b.HasOne("phase_2_back_end.Database.Canvas", null)
                        .WithMany("Rows")
                        .HasForeignKey("CanvasPictureID");
                });
#pragma warning restore 612, 618
        }
    }
}
